name: Build Multi-Platform Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  actions: read

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Setup FFmpeg
      run: |
        python -c "from downloader import Downloader; d = Downloader(); d.setup_ffmpeg(); print('FFmpeg setup completed')"
    
    - name: Build Windows executable
      run: |
        pyinstaller youtube_downloader.spec --clean --noconfirm
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: youtube-downloader-windows
        path: dist/YouTube-Downloader.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        
        # Install basic dependencies
        sudo apt-get install -y \
          libgtk-3-dev \
          libglib2.0-dev \
          libcairo2-dev \
          libpango1.0-dev \
          libgdk-pixbuf2.0-dev \
          libatk1.0-dev \
          pkg-config \
          build-essential \
          libffi-dev \
          libssl-dev \
          ffmpeg \
          xvfb
        
        # Try to install WebKit with fallback
        sudo apt-get install -y libwebkit2gtk-4.1-dev || \
        sudo apt-get install -y libwebkit2gtk-4.0-dev || \
        echo "WebKit dev packages not available"
        
        # Try to install JavaScriptCore with fallback
        sudo apt-get install -y libjavascriptcoregtk-4.1-dev || \
        sudo apt-get install -y libjavascriptcoregtk-4.0-dev || \
        echo "JavaScriptCore dev packages not available"
        
        # Try to install Soup with fallback
        sudo apt-get install -y libsoup-3.0-dev || \
        sudo apt-get install -y libsoup2.4-dev || \
        echo "Soup dev packages not available"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Setup FFmpeg (Skip download, use system)
      run: |
        python -c "import os; print('FFmpeg system installation:', os.system('ffmpeg -version'))"
    
    - name: Setup virtual display for GUI
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
    
    - name: Build Linux executable
      run: |
        export DISPLAY=:99
        pyinstaller youtube_downloader_linux.spec --clean --noconfirm
    
    - name: Make executable
      run: |
        chmod +x dist/YouTube-Downloader-Linux
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: youtube-downloader-linux
        path: dist/YouTube-Downloader-Linux

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        brew update
        brew install ffmpeg pkg-config
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Setup FFmpeg (Skip download, use system)
      run: |
        python -c "import os; print('FFmpeg system installation:', os.system('ffmpeg -version'))"
    
    - name: Build macOS executable
      run: |
        pyinstaller youtube_downloader_macos.spec --clean --noconfirm
    
    - name: Create DMG (Optional)
      run: |
        if command -v create-dmg &> /dev/null; then
          create-dmg \
            --volname "YouTube Downloader" \
            --window-pos 200 120 \
            --window-size 600 300 \
            --icon-size 100 \
            --icon "YouTube-Downloader-macOS.app" 175 120 \
            --hide-extension "YouTube-Downloader-macOS.app" \
            --app-drop-link 425 120 \
            "dist/YouTube-Downloader-macOS.dmg" \
            "dist/YouTube-Downloader-macOS.app" || true
        else
          echo "create-dmg not available, skipping DMG creation"
        fi
    
    - name: Upload macOS app artifact
      uses: actions/upload-artifact@v4
      with:
        name: youtube-downloader-macos-app
        path: dist/YouTube-Downloader-macOS.app
    
    - name: Upload macOS DMG artifact (if exists)
      uses: actions/upload-artifact@v4
      with:
        name: youtube-downloader-macos-dmg
        path: dist/YouTube-Downloader-macOS.dmg
      if: always()
      continue-on-error: true

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      actions: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create release archives
      run: |
        # Create archives for better organization
        cd youtube-downloader-windows && zip -r ../YouTube-Downloader-Windows.zip . && cd ..
        cd youtube-downloader-linux && tar -czf ../YouTube-Downloader-Linux.tar.gz . && cd ..
        cd youtube-downloader-macos-app && zip -r ../YouTube-Downloader-macOS.zip . && cd ..
        
        # List all files for verification
        ls -la
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          YouTube-Downloader-Windows.zip
          YouTube-Downloader-Linux.tar.gz
          YouTube-Downloader-macOS.zip
          youtube-downloader-macos-dmg/YouTube-Downloader-macOS.dmg
        body: |
          ## YouTube Downloader - Multi-Platform Release
          
          ### 📥 Download Instructions
          
          **Windows:**
          - Download `YouTube-Downloader-Windows.zip`
          - Extract and run `YouTube-Downloader.exe`
          
          **Linux:**
          - Download `YouTube-Downloader-Linux.tar.gz`
          - Extract: `tar -xzf YouTube-Downloader-Linux.tar.gz`
          - Run: `./YouTube-Downloader-Linux`
          
          **macOS:**
          - Download `YouTube-Downloader-macOS.dmg` (recommended)
          - Or download `YouTube-Downloader-macOS.zip` and extract
          - Run the app from Applications or directly
          
          ### ✨ Features
          - Download individual videos, playlists, or entire channels
          - Multiple quality options (720p, 1080p, 4K, etc.)
          - Subtitle support with multiple languages
          - Progress tracking for multiple downloads
          - Cookie support for member-only content
          - Built-in FFmpeg for video processing
          
          ### 🛠️ Requirements
          - No additional software required
          - All dependencies are bundled
          - FFmpeg included for video processing
          
          ### 📋 Changelog
          - Multi-platform support (Windows, Linux, macOS)
          - Improved UI with real-time progress tracking
          - Enhanced error handling and diagnostics
          - Subtitle embedding capabilities
          - Concurrent download support
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 